from regex_engine.domain.models.categorized_ingredient import CategorizedIngredient


class CategoryRepository:
    def load(self) -> dict[str, CategorizedIngredient]: ...
    def save(self, categorized_ingredients: dict[str, CategorizedIngredient]) -> None: ...
