from typing import Protocol, Iterable

from regex_engine.domain.models.resolved_ingredient import ResolvedIngredient
from regex_engine.adapters.input_adapters.types import EngineInput
from regex_engine.domain.enums import Category
from regex_engine.domain.models.registry_container import RegistryContainerReader


class IngredientRegexEngine(Protocol):
    async def learn(self, data:EngineInput, iterations:int = 10) -> list[ResolvedIngredient]: ...
    def recognize_ingredients(self, data:EngineInput) -> list[ResolvedIngredient]: ...
    async def categorize_registries(self) -> dict[str, Category]: ...
    def save_registries(self) -> None: ...
    def get_registries(self) -> RegistryContainerReader: ...
    def save_categories(self) -> None: ...