
from typing import Protocol, Optional, Sequence

from regex_engine.domain.enums import RegexKind
from regex_engine.domain.models.ingredient_regex_registry import IngredientRegexRegistry
from regex_engine.domain.models.regex_entry import RegexEntry
from regex_engine.domain.models.regex_registry import RegexRegistry


class RegexRegistryWriter(Protocol):
    def add_entry(self, entry:RegexEntry) -> None: ...
    def remove_entry(self, stem:str) -> None: ...
    def add_variant(self, *, stem:str, variant:str) -> None: ...
    def remove_variant(self, *, stem:str, variant:str) -> None: ...

class RegexRegistryReader(Protocol):
    def get(self, stem:str) -> Optional[RegexEntry]: ...
    def get_all(self) -> Sequence[RegexEntry]: ...
    def match_best(self, text:str) -> Optional[RegexEntry]: ...
    def swap_match(self, text:str) -> str: ...

class RegexRegistryStore(Protocol):
    def load(self) -> list[RegexEntry]: ...
    def save(self, entries: list[RegexEntry]) -> None: ...


class RegexRegistryRepository(Protocol):
    async def load(self, kind: RegexKind) -> RegexRegistry: ...
    async def save(self, kind: RegexKind, registry: RegexRegistry) -> None: ...


class IngredientRegexRegistryRepository(Protocol):
    async def load(self) -> IngredientRegexRegistry: ...
    async def save(self, registry: IngredientRegexRegistry) -> None: ...




