from typing import Protocol


class RegexResolver(Protocol):
    def standardize(self, ingredient:str) -> str: ...
    def can_be_standardized(self, ingredient:str) -> bool: ...
    def get_remainder(self, ingredient:str) -> str: ...
    def contains_conjunction(self, ingredient:str) -> bool:...
    def and_conjunction_between_numbers(self, ingredient:str) -> bool: ...