
from typing import Protocol, Optional, Sequence

from regex_engine.domain.enums import RegexKind
from regex_engine.domain.models.regex_entry import RegexEntry



class RegexRegistryWriter(Protocol):
    def add_entry(self, entry:RegexEntry) -> None: ...
    def remove_entry(self, stem:str) -> None: ...
    def add_variant(self, *, stem:str, variant:str) -> None: ...
    def remove_variant(self, *, stem:str, variant:str) -> None: ...

class RegexRegistryReader(Protocol):
    @property
    def kind(self) -> RegexKind: ...
    def get(self, stem:str) -> Optional[RegexEntry]: ...
    def get_all(self) -> Sequence[RegexEntry]: ...
    def match_best(self, text:str) -> Optional[RegexEntry]: ...
    def swap_match(self, text:str, replacement: str) -> str: ...


class RegexRegistry(RegexRegistryWriter, RegexRegistryReader, Protocol):
    pass

class RegexRegistryRepository(Protocol):
    def load(self, kind: RegexKind) -> RegexRegistry: ...
    def save(self, registry: RegexRegistry) -> None: ...




