
"""Init

Revision ID: 51ed5d6135cf
Revises: 
Create Date: 2026-05-18 11:03:27.433360

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '51ed5d6135cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorized_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stem', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stem')
    )
    op.create_table('regex_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('regex_kind', sa.String(), nullable=False),
    sa.Column('stem', sa.String(), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('categorized_ingredient_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['categorized_ingredient_id'], ['categorized_ingredients.id'], ),
    sa.PrimaryKeyConstraint('id', 'regex_kind'),
    sa.UniqueConstraint('stem')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regex_entries')
    op.drop_table('categorized_ingredients')
    # ### end Alembic commands ###
